name: Pull Request

on: [pull_request]

jobs:

  deploy_to_test_domain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies and build project
        run: |
          npm install
          npm run build
      - id: vk-miniapps-deploy
        run: |
          deploy_output_line=$(./node_modules/@vkontakte/vk-miniapps-deploy/bin/vk-miniapps-deploy | tail -1)
          echo "::set-output name=VK_MINIAPPS_DEPLOY_OUTPUT::$deploy_output_line"
        env:
          MINI_APPS_ACCESS_TOKEN: ${{ secrets.MINI_APPS_ACCESS_TOKEN }}
          MINI_APPS_ENVIRONMENT: dev
      - uses: actions/github-script@v6
        with:
          script: |
            const { run } = await import('${{ github.workspace }}/scripts/testDomainDeploy.js')
            await run({context})
        env:
          VK_MINIAPPS_DEPLOY_OUTPUT: ${{ steps.vk-miniapps-deploy.outputs.VK_MINIAPPS_DEPLOY_OUTPUT }}
          MINI_APPS_ACCESS_TOKEN: ${{ secrets.MINI_APPS_ACCESS_TOKEN }}
